name: Bug Report
description: Report an issue about using Bazzite
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report! The Bazzite team will NEVER ask you to download arbritary files from the internet, help us keep GitHub clean by reporting phishing links.
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
      value: "When I entered 2 + 2, I got the answer 6."
    validations:
      required: true
  - type: textarea
    id: expected-bahavior
    attributes:
      label: What did you expect to happen?
      description: A clear and concise description of what you expected to happen.
      placeholder: What were you expecting to happen?
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Session Logs
      description: Generate a bug report from HHD or `journalctl -b | fpaste` and paste the link here.
      render: shell
    validations:
      required: true
  - type: textarea
    id: hardware
    attributes:
      label: Hardware
      description: What is the model of your hardware? (e.g. Steam Deck, Aya Neo, etc.)
    validations:
      required: true
  - type: textarea
    id: extra-context
    attributes:
      label: Extra information or context
      description: Add any other context about the problem here.
